<#
.SYNOPSIS
    Drive real agent harnesses — Codex CLI, and Claude Code when a Claude deployment exists —
    against the gateway, then into its 429 and 403 walls.

.DESCRIPTION
    Stage 4 of the cycle, and the one the owner actually asked for: *"demonstrate that we are
    able to start codex harnesses locally pointed at the foundry resource and that the quota
    and measurement works."* curl proves the gateway; this proves the developer experience.

    Codex runs against an ISOLATED CODEX_HOME under the state directory, so the operator's
    own ~/.codex/config.toml, auth and session history are never read or written. The
    config.toml is exactly the shape documented in getting-started/cli-setup.mdx, including
    the one non-obvious line:

        env_http_headers = { "api-key" = "FOUNDRYGATE_API_KEY" }

    `env_key` alone makes Codex send `Authorization: Bearer`, which the gateway rejects with
    401 (E-010, verified live 2026-09-01). If this script's happy path ever starts returning
    401, that is the first thing to check.

    dev-bob is the subject: a standard-tier key whose small monthly budget smoke.ps1
    deliberately leaves intact. The script does three things in order —

      C1  a successful `codex exec` through the gateway
      C2  keep running `codex exec` until the gateway answers 429 (TPM) and record what
          Codex does about it (exit code, stderr)
      C3  keep going until the monthly budget is spent and the gateway answers 403, and
          record what Codex does about that

    and then, if a Claude deployment reached Succeeded, a Claude Code pass (`claude -p`)
    with the Foundry env vars from the same doc page. Claude Code is SKIPped, not failed,
    when no Claude deployment exists.

.EXAMPLE
    pwsh scripts/cycle/codex-test.ps1
#>
[CmdletBinding()]
param(
    [string] $Environment = 'test',
    [Parameter(HelpMessage = 'Cap on total codex exec invocations before giving up on reaching 403.')]
    [int] $MaxExecs = 25,
    [Parameter(HelpMessage = 'Wall-clock cap for the whole harness stage.')]
    [int] $TimeoutMinutes = 30
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/_common.ps1"

$state = Get-CycleState -Environment $Environment -Required
$openaiUrl = $state.outputs.openaiApiUrl
$anthropicUrl = $state.outputs.anthropicApiUrl
$bobKey = $state.apimSubscriptions['dev-bob'].primaryKey
$failures = 0

function Assert-Check {
    param([string] $Id, [string] $Name, [bool] $Condition, [string] $Detail)
    Add-CycleCheck -State $state -Id $Id -Name $Name -Status ($Condition ? 'PASS' : 'FAIL') -Detail $Detail
    if (-not $Condition) { $script:failures++ }
}

# ---- Isolated CODEX_HOME ----------------------------------------------------------
$codexHome = Join-Path (Split-Path (Get-CycleStatePath -Environment $Environment)) "codex-home-$Environment"
$codexWork = Join-Path (Split-Path (Get-CycleStatePath -Environment $Environment)) "codex-work-$Environment"
foreach ($d in @($codexHome, $codexWork)) {
    if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

$configToml = @"
# Generated by scripts/cycle/codex-test.ps1. Mirrors the Codex CLI block in
# docs-site/src/content/docs/getting-started/cli-setup.mdx exactly.
model = "gpt"
model_provider = "azure"

[model_providers.azure]
name = "Azure via FoundryGate"
base_url = "$openaiUrl"
wire_api = "responses"
# REQUIRED: env_key alone sends "Authorization: Bearer", which the gateway 401s (E-010).
env_http_headers = { "api-key" = "FOUNDRYGATE_API_KEY" }
"@
Set-Content -Path (Join-Path $codexHome 'config.toml') -Value $configToml -Encoding utf8
Write-CycleInfo "CODEX_HOME=$codexHome (isolated), base_url=$openaiUrl"

<#
 One non-interactive codex run. Returns exit code, stdout and stderr. The sandbox and
 approval flags matter: without them codex can block on an approval prompt with no TTY,
 and this script must never wait on a human.
#>
function Invoke-CodexExec {
    param([Parameter(Mandatory)][string] $Prompt)
    $outFile = [System.IO.Path]::GetTempFileName()
    $errFile = [System.IO.Path]::GetTempFileName()
    try {
        $env:CODEX_HOME = $codexHome
        $env:FOUNDRYGATE_API_KEY = $bobKey
        $p = Start-Process -FilePath 'codex' -NoNewWindow -Wait -PassThru `
            -ArgumentList @(
            'exec',
            '--skip-git-repo-check',
            '--sandbox', 'read-only',
            '--cd', $codexWork,
            '--color', 'never',
            $Prompt
        ) -RedirectStandardOutput $outFile -RedirectStandardError $errFile
        return [pscustomobject]@{
            ExitCode = $p.ExitCode
            StdOut   = (Get-Content -Path $outFile -Raw -ErrorAction SilentlyContinue) ?? ''
            StdErr   = (Get-Content -Path $errFile -Raw -ErrorAction SilentlyContinue) ?? ''
        }
    }
    finally {
        Remove-Item -Path $outFile, $errFile -Force -ErrorAction SilentlyContinue
        Remove-Item Env:FOUNDRYGATE_API_KEY -ErrorAction SilentlyContinue
    }
}

# What the gateway is currently telling dev-bob, independent of how Codex renders it.
# Codex retries and reshapes transport errors, so its own output is evidence of BEHAVIOUR;
# this probe is evidence of the gateway's ANSWER.
function Get-GatewayVerdict {
    $r = Invoke-GatewayRequest -Uri "$openaiUrl/chat/completions" -Headers @{ 'api-key' = $bobKey } `
        -Body (@{ model = 'gpt'; max_tokens = 8; messages = @(@{ role = 'user'; content = 'ping' }) } | ConvertTo-Json -Compress)
    return [pscustomobject]@{
        StatusCode     = $r.StatusCode
        RemainingTpm   = Get-ResponseHeader $r 'x-fg-remaining-tpm'
        RemainingQuota = Get-ResponseHeader $r 'x-fg-remaining-quota'
        RetryAfter     = Get-ResponseHeader $r 'Retry-After'
        FgError        = Get-ResponseHeader $r 'x-fg-error'
        Body           = $r.Body
    }
}

# ---- C1: a real Codex session through the gateway ---------------------------------
Write-CycleHeading 'C1 — codex exec through the gateway'
$first = Invoke-CodexExec -Prompt 'Reply with exactly the single word: pong. Do not run any commands.'
$firstOk = $first.ExitCode -eq 0 -and ($first.StdOut -match '(?i)pong')
Assert-Check -Id 'C1' -Name 'codex exec completes against the gateway' -Condition $firstOk `
    -Detail "exit=$($first.ExitCode); stdout=$(Format-BodyExcerpt $first.StdOut 200); stderr=$(Format-BodyExcerpt $first.StdErr 200)"

if (-not $firstOk) {
    Write-Host '  Codex could not reach the gateway; skipping the 429/403 walls.' -ForegroundColor Yellow
    Add-CycleCheck -State $state -Id 'C2' -Name 'Codex observed behaviour at the TPM 429 wall' -Status 'SKIP' -Detail 'C1 did not succeed.'
    Add-CycleCheck -State $state -Id 'C3' -Name 'Codex observed behaviour at the monthly-quota 403 wall' -Status 'SKIP' -Detail 'C1 did not succeed.'
}
else {
    # ---- C2/C3: run codex until the gateway says 429, then until it says 403 -------
    # codex burns ~9K tokens per exec on its own system prompt (T11), so a standard-tier
    # key with a demo-sized budget hits both walls within a handful of runs.
    Write-CycleHeading 'C2/C3 — running codex exec until the gateway refuses'
    $deadline = (Get-Date).AddMinutes($TimeoutMinutes)
    $seen429 = $null
    $seen403 = $null
    $execs = 1
    while ($execs -lt $MaxExecs -and (Get-Date) -lt $deadline -and $null -eq $seen403) {
        $execs++
        $run = Invoke-CodexExec -Prompt "Write a 200-word explanation of TCP congestion control. Run number $execs. Do not run any commands."
        $verdict = Get-GatewayVerdict
        Write-CycleInfo ("exec {0}: codex exit={1}; gateway now {2} (tpm={3} quota={4})" -f $execs, $run.ExitCode, $verdict.StatusCode, $verdict.RemainingTpm, $verdict.RemainingQuota)

        if ($null -eq $seen429 -and ($verdict.StatusCode -eq 429 -or $run.StdErr -match '429')) {
            $seen429 = [pscustomobject]@{ Exec = $execs; Run = $run; Verdict = $verdict }
        }
        if ($verdict.StatusCode -eq 403 -and $verdict.FgError -eq '') {
            $seen403 = [pscustomobject]@{ Exec = $execs; Run = $run; Verdict = $verdict }
        }
    }

    if ($null -ne $seen429) {
        Assert-Check -Id 'C2' -Name 'Codex observed behaviour at the TPM 429 wall' -Condition $true `
            -Detail ("after {0} execs: gateway 429 Retry-After={1}, x-fg-remaining-tpm={2}; codex exit={3}; stderr={4}" -f `
                $seen429.Exec, $seen429.Verdict.RetryAfter, $seen429.Verdict.RemainingTpm, $seen429.Run.ExitCode, (Format-BodyExcerpt $seen429.Run.StdErr 240))
    }
    else {
        Add-CycleCheck -State $state -Id 'C2' -Name 'Codex observed behaviour at the TPM 429 wall' -Status 'SKIP' `
            -Detail "No 429 observed in $execs execs — the monthly quota was reached first (smoke.ps1 already proves the TPM path as T4a)."
    }

    if ($null -ne $seen403) {
        Assert-Check -Id 'C3' -Name 'Codex observed behaviour at the monthly-quota 403 wall' -Condition $true `
            -Detail ("after {0} execs: gateway 403 (native token-quota refusal), body={1}; codex exit={2}; stderr={3}" -f `
                $seen403.Exec, (Format-BodyExcerpt $seen403.Verdict.Body 200), $seen403.Run.ExitCode, (Format-BodyExcerpt $seen403.Run.StdErr 240))
    }
    else {
        Assert-Check -Id 'C3' -Name 'Codex observed behaviour at the monthly-quota 403 wall' -Condition $false `
            -Detail "dev-bob's monthly budget was not exhausted within $execs execs / $TimeoutMinutes min."
    }
    $state.codexExecCount = $execs
}

# ---- C4: Claude Code against the Anthropic front door -----------------------------
Write-CycleHeading 'C4 — Claude Code (Foundry mode) through the gateway'
if (-not [bool]$state.claudeAvailable) {
    Add-CycleCheck -State $state -Id 'C4' -Name 'claude -p completes against the gateway (Foundry mode)' -Status 'SKIP' `
        -Detail 'No Anthropic deployment reached Succeeded on this cycle (E-007), so the Claude Code env-var block is not verified by this run.'
}
else {
    $carolKey = $state.apimSubscriptions['dev-carol'].primaryKey
    $claudeWork = Join-Path (Split-Path (Get-CycleStatePath -Environment $Environment)) "claude-work-$Environment"
    if (-not (Test-Path $claudeWork)) { New-Item -ItemType Directory -Path $claudeWork -Force | Out-Null }
    $outFile = [System.IO.Path]::GetTempFileName()
    $errFile = [System.IO.Path]::GetTempFileName()
    try {
        # Exactly the variables documented in getting-started/cli-setup.mdx.
        $env:CLAUDE_CODE_USE_FOUNDRY = '1'
        $env:ANTHROPIC_FOUNDRY_BASE_URL = $anthropicUrl
        $env:ANTHROPIC_FOUNDRY_API_KEY = $carolKey
        $env:ANTHROPIC_DEFAULT_SONNET_MODEL = 'sonnet'
        $env:ANTHROPIC_DEFAULT_HAIKU_MODEL = 'haiku'
        $env:ANTHROPIC_DEFAULT_OPUS_MODEL = 'sonnet'  # power tier has no opus alias; point it at one it does have
        $p = Start-Process -FilePath 'claude' -NoNewWindow -Wait -PassThru `
            -ArgumentList @('-p', 'reply with the single word pong') `
            -WorkingDirectory $claudeWork -RedirectStandardOutput $outFile -RedirectStandardError $errFile
        $out = (Get-Content -Path $outFile -Raw -ErrorAction SilentlyContinue) ?? ''
        $err = (Get-Content -Path $errFile -Raw -ErrorAction SilentlyContinue) ?? ''
        Assert-Check -Id 'C4' -Name 'claude -p completes against the gateway (Foundry mode)' `
            -Condition ($p.ExitCode -eq 0 -and $out -match '(?i)pong') `
            -Detail "exit=$($p.ExitCode); stdout=$(Format-BodyExcerpt $out 200); stderr=$(Format-BodyExcerpt $err 200)"
    }
    finally {
        Remove-Item -Path $outFile, $errFile -Force -ErrorAction SilentlyContinue
        foreach ($v in 'CLAUDE_CODE_USE_FOUNDRY', 'ANTHROPIC_FOUNDRY_BASE_URL', 'ANTHROPIC_FOUNDRY_API_KEY',
            'ANTHROPIC_DEFAULT_SONNET_MODEL', 'ANTHROPIC_DEFAULT_HAIKU_MODEL', 'ANTHROPIC_DEFAULT_OPUS_MODEL') {
            Remove-Item "Env:$v" -ErrorAction SilentlyContinue
        }
    }
}

$state.harnessCompletedUtc = (Get-Date).ToUniversalTime().ToString('o')
Save-CycleState -State $state

if ($failures -gt 0) { Write-Host "$failures harness check(s) FAILED." -ForegroundColor Red; exit 1 }
Write-Host 'Harness checks complete.' -ForegroundColor Green
exit 0
