<#
.SYNOPSIS
    Drive real agent harnesses — Codex CLI, and Claude Code when a Claude deployment exists —
    against the gateway, then into its 429 and 403 walls.

.DESCRIPTION
    Stage 4 of the cycle, and the one the owner actually asked for: *"demonstrate that we are
    able to start codex harnesses locally pointed at the foundry resource and that the quota
    and measurement works."* curl proves the gateway; this proves the developer experience.

    Codex runs against an ISOLATED CODEX_HOME under the state directory, so the operator's
    own ~/.codex/config.toml, auth and session history are never read or written. The
    config.toml is exactly the shape documented in getting-started/cli-setup.mdx, including
    the one non-obvious line:

        env_http_headers = { "api-key" = "FOUNDRYGATE_API_KEY" }

    `env_key` alone makes Codex send `Authorization: Bearer`, which the gateway rejects with
    401 (E-010, verified live 2026-09-01). If this script's happy path ever starts returning
    401, that is the first thing to check.

    TWO KEYS, ON PURPOSE.

      C1  runs as dev-carol (power tier). The happy path deserves a tier a real agent
          harness would actually be issued: `codex exec` burns ~9K tokens per run on its
          system prompt alone, so a standard-tier key's 8K/minute cap throttles Codex
          *inside* its first session and "does Codex work at all" would be measuring the
          wrong thing.
      C2  runs as dev-bob (standard tier, tight TPM). One or two execs put him through the
          TPM wall, and what Codex does there is the finding: it 429s, retries, keeps the
          bucket empty and eventually gives up with exit 1 without completing the exec.
      C3  runs as dev-carol (power tier: generous TPM, small monthly budget). That is the
          only shape in which a harness can reach the MONTHLY wall — from behind a tight TPM
          cap codex never finishes an exec and so never spends its monthly budget at all
          (#237, observed live across 25 consecutive execs at both 8000 and 12000 TPM).

    Each wall records what Codex did — exit code and stderr — next to the gateway's own
    answer, probed independently, because Codex reshapes and retries what it is told.

    and then, if a Claude deployment reached Succeeded, a Claude Code pass (`claude -p`)
    with the Foundry env vars from the same doc page. Claude Code is SKIPped, not failed,
    when no Claude deployment exists.

.EXAMPLE
    pwsh scripts/cycle/codex-test.ps1
#>
[CmdletBinding()]
param(
    [string] $Environment = 'test',
    [Parameter(HelpMessage = 'Cap on total codex exec invocations before giving up on reaching 403.')]
    [int] $MaxExecs = 25,
    [Parameter(HelpMessage = 'Wall-clock cap for the whole harness stage.')]
    [int] $TimeoutMinutes = 30
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/_common.ps1"

$state = Get-CycleState -Environment $Environment -Required
$openaiUrl = $state.outputs.openaiApiUrl
$anthropicUrl = $state.outputs.anthropicApiUrl
$bobKey = $state.apimSubscriptions['dev-bob'].primaryKey
$carolKey = $state.apimSubscriptions['dev-carol'].primaryKey
$failures = 0

function Assert-Check {
    param([string] $Id, [string] $Name, [bool] $Condition, [string] $Detail)
    Add-CycleCheck -State $state -Id $Id -Name $Name -Status ($Condition ? 'PASS' : 'FAIL') -Detail $Detail
    if (-not $Condition) { $script:failures++ }
}

# ---- Isolated CODEX_HOME ----------------------------------------------------------
$codexHome = Join-Path (Split-Path (Get-CycleStatePath -Environment $Environment)) "codex-home-$Environment"
$codexWork = Join-Path (Split-Path (Get-CycleStatePath -Environment $Environment)) "codex-work-$Environment"
foreach ($d in @($codexHome, $codexWork)) {
    if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

$configToml = @"
# Generated by scripts/cycle/codex-test.ps1. Mirrors the Codex CLI block in
# docs-site/src/content/docs/getting-started/cli-setup.mdx exactly.
model = "gpt"
model_provider = "azure"

[model_providers.azure]
name = "Azure via FoundryGate"
base_url = "$openaiUrl"
wire_api = "responses"
# REQUIRED: env_key alone sends "Authorization: Bearer", which the gateway 401s (E-010).
env_http_headers = { "api-key" = "FOUNDRYGATE_API_KEY" }
"@
Set-Content -Path (Join-Path $codexHome 'config.toml') -Value $configToml -Encoding utf8
Write-CycleInfo "CODEX_HOME=$codexHome (isolated), base_url=$openaiUrl"

<#
 One non-interactive codex run. Returns exit code, stdout and stderr. The sandbox and
 approval flags matter: without them codex can block on an approval prompt with no TTY,
 and this script must never wait on a human.
#>
function Resolve-CliPath {
    param([Parameter(Mandatory)][string] $Name)
    # Start-Process needs a real file, and on Windows both CLIs ship as shims — codex is a
    # .cmd next to a extension-less shell script, claude is an .exe. `codex` alone resolves
    # to the extension-less file, which Start-Process cannot launch.
    # -All matters: `codex` resolves to THREE commands on Windows (codex.ps1, codex.cmd and an
    # extension-less shell script), and Get-Command without -All returns whichever the
    # resolution order picks — often the extension-less one, which Start-Process cannot launch.
    $candidates = @(Get-Command $Name -All -ErrorAction SilentlyContinue |
            Where-Object { $_.CommandType -eq [System.Management.Automation.CommandTypes]::Application })
    if ($candidates.Count -eq 0) { return $null }
    $launchable = @($candidates | Where-Object { $_.Source -match '\.(cmd|bat|exe)$' })
    if ($launchable.Count -gt 0) { return $launchable[0].Source }
    return $candidates[0].Source
}

$codexPath = Resolve-CliPath -Name 'codex'
if (-not $codexPath) { throw "codex CLI not found on PATH. Install it, or run cycle.ps1 with -SkipHarness." }
Write-CycleInfo "codex: $codexPath"

function Invoke-CodexExec {
    param(
        [Parameter(Mandatory)][string] $Prompt,
        [Parameter(Mandatory)][string] $Key
    )
    $outFile = [System.IO.Path]::GetTempFileName()
    $errFile = [System.IO.Path]::GetTempFileName()
    $inFile = [System.IO.Path]::GetTempFileName()
    try {
        # The prompt goes in on STDIN, not as an argument. Start-Process joins -ArgumentList
        # with spaces and does no quoting, so a multi-word prompt arrives as several
        # arguments and codex refuses with "unexpected argument 'with' found". `codex exec`
        # reads its instructions from stdin when no PROMPT argument is given, which sidesteps
        # the quoting problem entirely and has no length limit.
        Set-Content -Path $inFile -Value $Prompt -Encoding utf8
        $env:CODEX_HOME = $codexHome
        $env:FOUNDRYGATE_API_KEY = $Key
        $p = Start-Process -FilePath $codexPath -NoNewWindow -Wait -PassThru `
            -ArgumentList @(
            'exec',
            '--skip-git-repo-check',
            '--sandbox', 'read-only',
            '--cd', "`"$codexWork`"",
            '--color', 'never'
        ) -RedirectStandardInput $inFile -RedirectStandardOutput $outFile -RedirectStandardError $errFile
        return [pscustomobject]@{
            ExitCode = $p.ExitCode
            StdOut   = (Get-Content -Path $outFile -Raw -ErrorAction SilentlyContinue) ?? ''
            StdErr   = (Get-Content -Path $errFile -Raw -ErrorAction SilentlyContinue) ?? ''
        }
    }
    finally {
        Remove-Item -Path $outFile, $errFile, $inFile -Force -ErrorAction SilentlyContinue
        Remove-Item Env:FOUNDRYGATE_API_KEY -ErrorAction SilentlyContinue
    }
}

# What the gateway is currently telling a given key, independent of how Codex renders it.
# Codex retries and reshapes transport errors, so its own output is evidence of BEHAVIOUR;
# this probe is evidence of the gateway's ANSWER.
function Get-GatewayVerdict {
    param([Parameter(Mandatory)][string] $Key)
    $r = Invoke-GatewayRequest -Uri "$openaiUrl/chat/completions" -Headers @{ 'api-key' = $Key } `
        -Body (@{ model = 'gpt'; max_tokens = 8; messages = @(@{ role = 'user'; content = 'ping' }) } | ConvertTo-Json -Compress)
    return [pscustomobject]@{
        StatusCode     = $r.StatusCode
        RemainingTpm   = Get-ResponseHeader $r 'x-fg-remaining-tpm'
        RemainingQuota = Get-ResponseHeader $r 'x-fg-remaining-quota'
        RetryAfter     = Get-ResponseHeader $r 'Retry-After'
        FgError        = Get-ResponseHeader $r 'x-fg-error'
        Body           = $r.Body
    }
}

# ---- C1: a real Codex session through the gateway ---------------------------------
Write-CycleHeading 'C1 — codex exec through the gateway (dev-carol, power tier)'
$first = Invoke-CodexExec -Key $carolKey -Prompt 'Reply with exactly the single word: pong. Do not run any commands.'
$firstOk = $first.ExitCode -eq 0 -and ($first.StdOut -match '(?i)pong')
Assert-Check -Id 'C1' -Name 'codex exec completes against the gateway (power tier)' -Condition $firstOk `
    -Detail "exit=$($first.ExitCode); stdout=$(Format-BodyExcerpt $first.StdOut 200); stderr=$(Format-BodyExcerpt $first.StdErr 200)"

if (-not $firstOk) {
    Write-Host '  Codex could not reach the gateway; skipping the 429/403 walls.' -ForegroundColor Yellow
    Add-CycleCheck -State $state -Id 'C2' -Name 'Codex observed behaviour at the TPM 429 wall' -Status 'SKIP' -Detail 'C1 did not succeed.'
    Add-CycleCheck -State $state -Id 'C3' -Name 'Codex observed behaviour at the monthly-quota 403 wall' -Status 'SKIP' -Detail 'C1 did not succeed.'
}
else {
    $totalExecs = 1

    # ---- C2: the TPM wall, on the tight-TPM tier ----------------------------------
    # One exec is enough: codex spends ~9-10K tokens on its system prompt, which is most of
    # a standard-tier minute, so the 429 arrives inside the first or second session.
    Write-CycleHeading 'C2 — codex exec as dev-bob (standard tier, tight TPM) until the gateway says 429'
    $seen429 = $null
    $bobExecs = 0
    while ($bobExecs -lt 3 -and $null -eq $seen429) {
        $bobExecs++; $totalExecs++
        $run = Invoke-CodexExec -Key $bobKey -Prompt "Write a 200-word explanation of TCP congestion control. Run number $bobExecs. Do not run any commands."
        $verdict = Get-GatewayVerdict -Key $bobKey
        Write-CycleInfo ("dev-bob exec {0}: codex exit={1}; gateway now {2} (tpm={3} quota={4})" -f $bobExecs, $run.ExitCode, $verdict.StatusCode, $verdict.RemainingTpm, $verdict.RemainingQuota)
        if ($verdict.StatusCode -eq 429 -or $run.StdErr -match '429') {
            $seen429 = [pscustomobject]@{ Exec = $bobExecs; Run = $run; Verdict = $verdict }
        }
    }

    if ($null -ne $seen429) {
        Assert-Check -Id 'C2' -Name 'Codex observed behaviour at the TPM 429 wall' -Condition $true `
            -Detail ("after {0} exec(s): gateway 429 Retry-After={1}, x-fg-remaining-tpm={2}; codex exit={3}; stderr={4}" -f `
                $seen429.Exec, $seen429.Verdict.RetryAfter, $seen429.Verdict.RemainingTpm, $seen429.Run.ExitCode, (Format-BodyExcerpt $seen429.Run.StdErr 240))
    }
    else {
        Add-CycleCheck -State $state -Id 'C2' -Name 'Codex observed behaviour at the TPM 429 wall' -Status 'SKIP' `
            -Detail "No 429 in $bobExecs execs against the standard tier (smoke.ps1 proves the TPM path independently as T4a)."
    }

    # ---- C3: the monthly wall, on the generous-TPM tier ---------------------------
    # It HAS to be this tier. From behind a tight TPM cap codex 429s, retries, keeps the
    # bucket empty and gives up without finishing an exec — so it never spends its monthly
    # budget and the 403 is unreachable (#237, seen across 25 consecutive execs at both 8000
    # and 12000 TPM). With TPM well above one exec, each run completes and the small monthly
    # budget is gone in a handful of them.
    Write-CycleHeading 'C3 — codex exec as dev-carol (power tier, generous TPM, small monthly budget) until the gateway says 403'
    $deadline = (Get-Date).AddMinutes($TimeoutMinutes)
    $seen403 = $null
    $carolExecs = 0
    while ($totalExecs -lt $MaxExecs -and (Get-Date) -lt $deadline -and $null -eq $seen403) {
        $carolExecs++; $totalExecs++
        $run = Invoke-CodexExec -Key $carolKey -Prompt "Write a 200-word explanation of TCP congestion control. Run number $carolExecs. Do not run any commands."
        $verdict = Get-GatewayVerdict -Key $carolKey
        Write-CycleInfo ("dev-carol exec {0}: codex exit={1}; gateway now {2} (tpm={3} quota={4})" -f $carolExecs, $run.ExitCode, $verdict.StatusCode, $verdict.RemainingTpm, $verdict.RemainingQuota)
        # Our own policy denials always set x-fg-error; a bare 403 is APIM's native
        # token-quota refusal, which is the thing under test.
        if ($verdict.StatusCode -eq 403 -and $verdict.FgError -eq '') {
            $seen403 = [pscustomobject]@{ Exec = $carolExecs; Run = $run; Verdict = $verdict }
        }
    }

    if ($null -ne $seen403) {
        Assert-Check -Id 'C3' -Name 'Codex observed behaviour at the monthly-quota 403 wall' -Condition $true `
            -Detail ("after {0} execs: gateway 403 (native token-quota refusal), body={1}; codex exit={2}; stderr={3}" -f `
                $seen403.Exec, (Format-BodyExcerpt $seen403.Verdict.Body 200), $seen403.Run.ExitCode, (Format-BodyExcerpt $seen403.Run.StdErr 240))
    }
    else {
        Assert-Check -Id 'C3' -Name 'Codex observed behaviour at the monthly-quota 403 wall' -Condition $false `
            -Detail "dev-carol's monthly budget was not exhausted within $carolExecs execs / $TimeoutMinutes min."
    }
    $state.codexExecCount = $totalExecs
}

# ---- C4: Claude Code against the Anthropic front door -----------------------------
Write-CycleHeading 'C4 — Claude Code (Foundry mode) through the gateway'
if (-not [bool]$state.claudeAvailable) {
    Add-CycleCheck -State $state -Id 'C4' -Name 'claude -p completes against the gateway (Foundry mode)' -Status 'SKIP' `
        -Detail 'No Anthropic deployment reached Succeeded on this cycle (E-007), so the Claude Code env-var block is not verified by this run.'
}
elseif (-not ($claudePath = Resolve-CliPath -Name 'claude')) {
    Add-CycleCheck -State $state -Id 'C4' -Name 'claude -p completes against the gateway (Foundry mode)' -Status 'SKIP' `
        -Detail 'A Claude deployment exists, but the claude CLI is not on PATH on this machine.'
}
else {
    $claudeWork = Join-Path (Split-Path (Get-CycleStatePath -Environment $Environment)) "claude-work-$Environment"
    if (-not (Test-Path $claudeWork)) { New-Item -ItemType Directory -Path $claudeWork -Force | Out-Null }
    $outFile = [System.IO.Path]::GetTempFileName()
    $errFile = [System.IO.Path]::GetTempFileName()
    try {
        # Exactly the variables documented in getting-started/cli-setup.mdx.
        $env:CLAUDE_CODE_USE_FOUNDRY = '1'
        $env:ANTHROPIC_FOUNDRY_BASE_URL = $anthropicUrl
        $env:ANTHROPIC_FOUNDRY_API_KEY = $carolKey
        $env:ANTHROPIC_DEFAULT_SONNET_MODEL = 'sonnet'
        $env:ANTHROPIC_DEFAULT_HAIKU_MODEL = 'haiku'
        $env:ANTHROPIC_DEFAULT_OPUS_MODEL = 'sonnet'  # power tier has no opus alias; point it at one it does have
        # Through Resolve-CliPath for the same reason codex is: Start-Process needs a real
        # launchable file, and a bare name can resolve to an extension-less shim it cannot run.
        $p = Start-Process -FilePath $claudePath -NoNewWindow -Wait -PassThru `
            -ArgumentList @('-p', 'reply with the single word pong') `
            -WorkingDirectory $claudeWork -RedirectStandardOutput $outFile -RedirectStandardError $errFile
        $out = (Get-Content -Path $outFile -Raw -ErrorAction SilentlyContinue) ?? ''
        $err = (Get-Content -Path $errFile -Raw -ErrorAction SilentlyContinue) ?? ''
        Assert-Check -Id 'C4' -Name 'claude -p completes against the gateway (Foundry mode)' `
            -Condition ($p.ExitCode -eq 0 -and $out -match '(?i)pong') `
            -Detail "exit=$($p.ExitCode); stdout=$(Format-BodyExcerpt $out 200); stderr=$(Format-BodyExcerpt $err 200)"
    }
    finally {
        Remove-Item -Path $outFile, $errFile -Force -ErrorAction SilentlyContinue
        foreach ($v in 'CLAUDE_CODE_USE_FOUNDRY', 'ANTHROPIC_FOUNDRY_BASE_URL', 'ANTHROPIC_FOUNDRY_API_KEY',
            'ANTHROPIC_DEFAULT_SONNET_MODEL', 'ANTHROPIC_DEFAULT_HAIKU_MODEL', 'ANTHROPIC_DEFAULT_OPUS_MODEL') {
            Remove-Item "Env:$v" -ErrorAction SilentlyContinue
        }
    }
}

$state.harnessCompletedUtc = Get-CycleTimestamp
Save-CycleState -State $state

if ($failures -gt 0) { Write-Host "$failures harness check(s) FAILED." -ForegroundColor Red; exit 1 }
Write-Host 'Harness checks complete.' -ForegroundColor Green
exit 0
