<#
.SYNOPSIS
    Render the cycle state file as a markdown evidence report.

.DESCRIPTION
    Called by cycle.ps1 at the end of a run, and safe to call by hand afterwards — the state
    file is the single source, so re-running measure.ps1 later (Log Analytics ingestion lags)
    and then re-rendering picks up the new numbers without repeating the whole cycle.

    Everything printed here is a recorded observation. Keys are redacted through
    Protect-CycleSecret on the way into the state file and again on the way out.

.EXAMPLE
    pwsh scripts/cycle/report.ps1 -Path validation/2026-09-05-gateway-cycle.md
#>
[CmdletBinding()]
param(
    [string] $Environment = 'test',
    [Parameter(Mandatory)][string] $Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/_common.ps1"

$state = Get-CycleState -Environment $Environment -Required
$sb = [System.Text.StringBuilder]::new()
function Add-Line { param([string] $Text = '') [void]$sb.AppendLine($Text) }

$when = if ($state.ContainsKey('upStartedUtc')) { [datetimeoffset]::Parse($state.upStartedUtc) } else { [datetimeoffset]::UtcNow }

Add-Line "# Gateway cycle — live evidence, $($when.ToString('yyyy-MM-dd'))"
Add-Line ''
Add-Line 'Generated by `scripts/cycle/cycle.ps1`. Every line below is an observation recorded during'
Add-Line 'the run, not a transcription. Re-render from the same state file with `scripts/cycle/report.ps1`.'
Add-Line ''

# ---- Summary ---------------------------------------------------------------------
$checks = @($state.ContainsKey('checks') ? $state.checks : @())
$pass = @($checks | Where-Object { $_.status -eq 'PASS' }).Count
$fail = @($checks | Where-Object { $_.status -eq 'FAIL' }).Count
$skip = @($checks | Where-Object { $_.status -eq 'SKIP' }).Count

Add-Line '## Summary'
Add-Line ''
Add-Line "| | |"
Add-Line "|---|---|"
Add-Line "| Subscription | $($state.subscription) |"
Add-Line "| Resource group | $($state.resourceGroup) ($($state.location)) |"
if ($state.ContainsKey('outputs')) {
    Add-Line "| Gateway URL | ``$($state.outputs.apimGatewayUrl)`` |"
    Add-Line "| Anthropic front door | ``$($state.outputs.anthropicApiUrl)`` |"
    Add-Line "| OpenAI front door | ``$($state.outputs.openaiApiUrl)`` |"
    Add-Line "| APIM | ``$($state.outputs.apimName)`` |"
    Add-Line "| Tier products | $((@($state.outputs.productIds) | ForEach-Object { "``$_``" }) -join ', ') |"
    Add-Line "| Log Analytics workspace | ``$($state.outputs.logAnalyticsWorkspaceName)`` (``$($state.outputs.logAnalyticsWorkspaceCustomerId)``) |"
    Add-Line "| Foundry accounts | $((@($state.outputs.foundryAccountNames) | ForEach-Object { "``$_``" }) -join ', ') |"
}
if ($state.ContainsKey('quotaTiers')) {
    $std = @($state.quotaTiers | Where-Object { $_.name -eq 'standard' })[0]
    Add-Line "| Standard tier under test | $($std.monthlyTokenQuota) tokens/month, $($std.tpm) TPM |"
}
Add-Line "| Claude deployment | $([bool]$state.claudeAvailable ? 'available' : '**not available** — see below') |"
Add-Line "| Teardown | $($state.ContainsKey('teardownMode') ? $state.teardownMode : 'not run') |"
Add-Line "| Checks | **$pass PASS**, $fail FAIL, $skip SKIP |"
if ($state.ContainsKey('cycleElapsedSeconds')) {
    Add-Line "| Wall clock | $([timespan]::FromSeconds([int]$state.cycleElapsedSeconds).ToString('hh\:mm\:ss')) |"
}
Add-Line ''

# ---- Timings ---------------------------------------------------------------------
if ($state.ContainsKey('stageResults')) {
    Add-Line '## Stage timings'
    Add-Line ''
    Add-Line '| Stage | Result | Duration |'
    Add-Line '|---|---|---|'
    foreach ($k in $state.stageResults.Keys) {
        $s = $state.stageResults[$k]
        Add-Line ("| ``{0}`` | {1} | {2} |" -f $k, ($s.ok ? 'OK' : 'FAILED'), [timespan]::FromSeconds([int]$s.seconds).ToString('mm\:ss'))
    }
    Add-Line ''
}

# ---- Checks ----------------------------------------------------------------------
Add-Line '## Checks'
Add-Line ''
Add-Line 'Raw header and body samples, keys redacted.'
Add-Line ''
Add-Line '| ID | Check | Result | Evidence |'
Add-Line '|---|---|---|---|'
foreach ($c in $checks) {
    $detail = (Protect-CycleSecret -Text ([string]$c.detail) -State $state) -replace '\|', '\|'
    Add-Line ("| ``{0}`` | {1} | **{2}** | {3} |" -f $c.id, $c.name, $c.status, $detail)
}
Add-Line ''

# ---- Model deployments -----------------------------------------------------------
if ($state.ContainsKey('modelDeployments')) {
    Add-Line '## Model deployments'
    Add-Line ''
    Add-Line '| Account | Deployment | Format | Provisioning state |'
    Add-Line '|---|---|---|---|'
    foreach ($account in $state.modelDeployments.Keys) {
        foreach ($d in @($state.modelDeployments[$account])) {
            Add-Line ("| ``{0}`` | ``{1}`` | {2} | {3} |" -f $account, $d.name, $d.format, $d.provisioningState)
        }
    }
    Add-Line ''
    if (-not [bool]$state.claudeAvailable) {
        Add-Line '> **Anthropic provisioning (E-007).** This cycle made exactly ONE Claude create attempt,'
        Add-Line '> through the day-0 ARM deploy, and it did not reach `Succeeded`. It was **not** retried and'
        Add-Line '> the deployment was **not** deleted and recreated: churn is what poisons an account for'
        Add-Line '> every later attempt. The demo continued on the OpenAI path, which is the primary harness'
        Add-Line '> path anyway (Codex).'
        if ($state.ContainsKey('claudeFailureDetail')) {
            Add-Line '>'
            Add-Line '> ```'
            Add-Line "> $($state.claudeFailureDetail)"
            Add-Line '> ```'
        }
        Add-Line ''
    }
}

# ---- Measurement -----------------------------------------------------------------
if ($state.ContainsKey('usageBySubscription') -and @($state.usageBySubscription).Count -gt 0) {
    Add-Line '## Measurement — `UsageBySubscription.kql` against the live workspace'
    Add-Line ''
    Add-Line '| APIM subscription | Prompt | Completion | Total | Requests |'
    Add-Line '|---|---|---|---|---|'
    foreach ($u in @($state.usageBySubscription)) {
        Add-Line ("| ``{0}`` | {1} | {2} | {3} | {4} |" -f $u.apimSubscriptionId, $u.promptTokens, $u.completionTokens, $u.totalTokens, $u.requestCount)
    }
    Add-Line ''
}

if ($state.ContainsKey('d017')) {
    $d = $state.d017
    Add-Line '### D-017 / #178 — the `max()` de-duplication assumption'
    Add-Line ''
    Add-Line "- Distinct `CorrelationId`s: **$($d.correlations)**"
    Add-Line "- With more than one log entry: **$($d.multiEntry)** (max $($d.maxEntriesPerRequest) entries for a single request)"
    Add-Line "- Naive `sum()` over every entry: **$($d.naiveSum)** tokens"
    Add-Line "- De-duplicated (`max()` per CorrelationId, then sum): **$($d.dedupedSum)** tokens"
    Add-Line "- Inflation a naive sum would have introduced: **$($d.inflationFactor)x**"
    Add-Line ''
}

# ---- How to reproduce ------------------------------------------------------------
Add-Line '## Reproducing this'
Add-Line ''
Add-Line '```sh'
Add-Line "pwsh scripts/cycle/cycle.ps1 -Subscription `"$($state.subscription)`""
Add-Line '```'
Add-Line ''
Add-Line 'See `.claude/skills/gateway-cycle/SKILL.md` for the unattended runbook, the Anthropic'
Add-Line 'create-once rules, and what each failure mode means.'
Add-Line ''

Set-Content -Path $Path -Value $sb.ToString() -Encoding utf8
Write-Host "Wrote $Path" -ForegroundColor Green
