<#
.SYNOPSIS
    Render the cycle state file as a markdown evidence report.

.DESCRIPTION
    Called by cycle.ps1 at the end of a run, and safe to call by hand afterwards — the state
    file is the single source, so re-running measure.ps1 later (Log Analytics ingestion lags)
    and then re-rendering picks up the new numbers without repeating the whole cycle.

    Everything printed here is a recorded observation. Keys are redacted by
    Protect-CycleSecret on the way INTO the state file, which is where the guarantee actually
    lives — by the time this runs in a full cycle, down.ps1 has already dropped
    apimSubscriptions from the state, so the second pass below has no key list left to match
    against and is defence in depth rather than the primary control.

.EXAMPLE
    pwsh scripts/cycle/report.ps1 -Path validation/2026-09-05-gateway-cycle.md
#>
[CmdletBinding()]
param(
    [string] $Environment = 'test',
    [Parameter(Mandatory)][string] $Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/_common.ps1"

$state = Get-CycleState -Environment $Environment -Required
$sb = [System.Text.StringBuilder]::new()
function Add-Line { param([string] $Text = '') [void]$sb.AppendLine($Text) }

# Markdown code spans. A literal backtick inside a double-quoted PowerShell string is the
# escape character, and a nested double-quoted string inside a subexpression inside another
# double-quoted string does not parse at all — which is how this script came to fail to parse
# entirely, silently producing no evidence report. Both problems go away with one helper
# built from a single-quoted backtick.
$script:Tick = '`'
function Format-Code { param([string] $Text) "$script:Tick$Text$script:Tick" }
function Format-CodeList { param($Items) (@($Items) | ForEach-Object { Format-Code ([string]$_) }) -join ', ' }

$when = if ($state.ContainsKey('upStartedUtc')) { ConvertFrom-CycleTimestamp $state.upStartedUtc } else { [datetimeoffset]::UtcNow }

Add-Line "# Gateway cycle — live evidence, $($when.ToString('yyyy-MM-dd'))"
Add-Line ''
Add-Line 'Generated by `scripts/cycle/cycle.ps1`. Every line below is an observation recorded during'
Add-Line 'the run, not a transcription. Re-render from the same state file with `scripts/cycle/report.ps1`.'
Add-Line ''

# ---- Summary ---------------------------------------------------------------------
$checks = @($state.ContainsKey('checks') ? $state.checks : @())
$pass = @($checks | Where-Object { $_.status -eq 'PASS' }).Count
$fail = @($checks | Where-Object { $_.status -eq 'FAIL' }).Count
$skip = @($checks | Where-Object { $_.status -eq 'SKIP' }).Count

Add-Line '## Summary'
Add-Line ''
Add-Line "| | |"
Add-Line "|---|---|"
Add-Line "| Subscription | $($state.subscription) |"
Add-Line "| Resource group | $($state.resourceGroup) ($($state.location)) |"
if ($state.ContainsKey('outputs')) {
    Add-Line ('| Gateway URL | {0} |' -f (Format-Code $state.outputs.apimGatewayUrl))
    Add-Line ('| Anthropic front door | {0} |' -f (Format-Code $state.outputs.anthropicApiUrl))
    Add-Line ('| OpenAI front door | {0} |' -f (Format-Code $state.outputs.openaiApiUrl))
    Add-Line ('| APIM | {0} |' -f (Format-Code $state.outputs.apimName))
    Add-Line ('| Tier products | {0} |' -f (Format-CodeList $state.outputs.productIds))
    Add-Line ('| Log Analytics workspace | {0} ({1}) |' -f (Format-Code $state.outputs.logAnalyticsWorkspaceName), (Format-Code $state.outputs.logAnalyticsWorkspaceCustomerId))
    Add-Line ('| Foundry accounts | {0} |' -f (Format-CodeList $state.outputs.foundryAccountNames))
}
$attached = $state.ContainsKey('attached') -and [bool]$state.attached
$modeText = if ($attached) { "**attached** to the already-deployed ``$($state.environment)`` environment — nothing deployed, nothing torn down" } else { 'deployed by this run' }
Add-Line "| Mode | $modeText |"
if ($state.ContainsKey('quotaTiers')) {
    # Every tier, not just standard. When the cycle deploys the gateway it also chose the
    # tiers, so "standard tier under test" said everything; attached to an environment it did
    # not shape, the tiers are a finding — they are what decides which walls are reachable at
    # all, and reading them back is how the SKIP-by-design rows below can be checked.
    foreach ($t in @($state.quotaTiers)) {
        $quotaText = ([int]$t.monthlyTokenQuota -gt 0) ? "$($t.monthlyTokenQuota) tokens/month" : 'no monthly quota'
        Add-Line ("| Tier {0} | {1}, {2} TPM |" -f (Format-Code $t.name), $quotaText, $t.tpm)
    }
}
# ContainsKey-guarded: up.ps1 writes claudeAvailable only after a successful deploy, and under
# Set-StrictMode a missing hashtable key THROWS. Unguarded, a failed `up` made report.ps1 throw
# from inside cycle.ps1's finally block — losing the evidence report in exactly the case it
# exists for.
$claudeState = if (-not $state.ContainsKey('claudeAvailable')) { 'not determined (the deploy did not get that far)' }
elseif ([bool]$state.claudeAvailable) { 'available' }
else { '**not available** — see below' }
Add-Line "| Claude deployment | $claudeState |"
Add-Line "| Teardown | $($state.ContainsKey('teardownMode') ? $state.teardownMode : 'not run') |"
Add-Line "| Checks | **$pass PASS**, $fail FAIL, $skip SKIP |"
if ($state.ContainsKey('cycleElapsedSeconds')) {
    Add-Line "| Wall clock | $([timespan]::FromSeconds([int]$state.cycleElapsedSeconds).ToString('hh\:mm\:ss')) |"
}
Add-Line ''

# ---- Timings ---------------------------------------------------------------------
if ($state.ContainsKey('stageResults')) {
    Add-Line '## Stage timings'
    Add-Line ''
    Add-Line '| Stage | Result | Duration |'
    Add-Line '|---|---|---|'
    foreach ($k in $state.stageResults.Keys) {
        $s = $state.stageResults[$k]
        Add-Line ("| ``{0}`` | {1} | {2} |" -f $k, ($s.ok ? 'OK' : 'FAILED'), [timespan]::FromSeconds([int]$s.seconds).ToString('mm\:ss'))
    }
    Add-Line ''
}

# ---- Checks ----------------------------------------------------------------------
Add-Line '## Checks'
Add-Line ''
Add-Line 'Raw header and body samples, keys redacted.'
Add-Line ''
Add-Line '| ID | Check | Result | Evidence |'
Add-Line '|---|---|---|---|'
foreach ($c in $checks) {
    $detail = (Protect-CycleSecret -Text ([string]$c.detail) -State $state) -replace '\|', '\|'
    Add-Line ("| ``{0}`` | {1} | **{2}** | {3} |" -f $c.id, $c.name, $c.status, $detail)
}
Add-Line ''

# ---- Model deployments -----------------------------------------------------------
if ($state.ContainsKey('modelDeployments')) {
    Add-Line '## Model deployments'
    Add-Line ''
    Add-Line '| Account | Deployment | Format | Provisioning state |'
    Add-Line '|---|---|---|---|'
    foreach ($account in $state.modelDeployments.Keys) {
        foreach ($d in @($state.modelDeployments[$account])) {
            Add-Line ("| ``{0}`` | ``{1}`` | {2} | {3} |" -f $account, $d.name, $d.format, $d.provisioningState)
        }
    }
    Add-Line ''
    if (-not [bool]$state.claudeAvailable) {
        Add-Line '> **Anthropic provisioning (E-007).** This cycle made exactly ONE Claude create attempt,'
        Add-Line '> through the day-0 ARM deploy, and it did not reach `Succeeded`. It was **not** retried and'
        Add-Line '> the deployment was **not** deleted and recreated: churn is what poisons an account for'
        Add-Line '> every later attempt. The demo continued on the OpenAI path, which is the primary harness'
        Add-Line '> path anyway (Codex).'
        if ($state.ContainsKey('claudeFailureDetail')) {
            Add-Line '>'
            Add-Line '> ```'
            Add-Line "> $($state.claudeFailureDetail)"
            Add-Line '> ```'
        }
        Add-Line ''
    }
}

# ---- Measurement -----------------------------------------------------------------
if ($state.ContainsKey('usageBySubscription') -and @($state.usageBySubscription).Count -gt 0) {
    Add-Line '## Measurement — `UsageBySubscription.kql` against the live workspace'
    Add-Line ''
    # The stage timing above can legitimately say FAILED while every M row below says PASS:
    # Log Analytics ingestion routinely lags the traffic by longer than the cycle takes, so
    # measure.ps1 is re-run afterwards. That is exactly why KeepFoundry keeps the workspace.
    if ($state.ContainsKey('stageResults') -and $state.stageResults.ContainsKey('measure') -and -not $state.stageResults['measure'].ok) {
        Add-Line '> The `measure` stage is marked FAILED in the timings above but the checks below PASS:'
        Add-Line '> Log Analytics had not finished ingesting when the stage ran inside the cycle, so'
        Add-Line '> `measure.ps1` was re-run against the same state file afterwards. The workspace survives'
        Add-Line '> a `KeepFoundry` teardown precisely so that is possible.'
        Add-Line ''
    }
    Add-Line '| APIM subscription | Prompt | Completion | Total | Requests |'
    Add-Line '|---|---|---|---|---|'
    foreach ($u in @($state.usageBySubscription)) {
        Add-Line ("| ``{0}`` | {1} | {2} | {3} | {4} |" -f $u.apimSubscriptionId, $u.promptTokens, $u.completionTokens, $u.totalTokens, $u.requestCount)
    }
    Add-Line ''
}

if ($state.ContainsKey('d017')) {
    $d = $state.d017
    Add-Line '### D-017 / #178 — the `max()` de-duplication assumption'
    Add-Line ''
    # Same backtick trap as above: in a double-quoted string `C would just escape the C and
    # the code span would silently vanish from the report.
    Add-Line ('- Distinct {0}s: **{1}**' -f (Format-Code 'CorrelationId'), $d.correlations)
    Add-Line "- With more than one log entry: **$($d.multiEntry)** (max $($d.maxEntriesPerRequest) entries for a single request)"
    Add-Line ('- Naive {0} over every entry: **{1}** tokens' -f (Format-Code 'sum()'), $d.naiveSum)
    Add-Line ('- De-duplicated ({0} per CorrelationId, then sum): **{1}** tokens' -f (Format-Code 'max()'), $d.dedupedSum)
    Add-Line "- Inflation a naive sum would have introduced: **$($d.inflationFactor)x**"
    Add-Line ''
}

# ---- How to reproduce ------------------------------------------------------------
Add-Line '## Reproducing this'
Add-Line ''
Add-Line '```sh'
$repro = "pwsh scripts/cycle/cycle.ps1 -Subscription `"$($state.subscription)`""
if ($attached) { $repro += " -Environment $($state.environment) -CleanupSubscriptions" }
Add-Line $repro
Add-Line '```'
Add-Line ''
Add-Line 'See `.claude/skills/gateway-cycle/SKILL.md` for the unattended runbook, the Anthropic'
Add-Line 'create-once rules, and what each failure mode means.'
Add-Line ''

Set-Content -Path $Path -Value $sb.ToString() -Encoding utf8
Write-Host "Wrote $Path" -ForegroundColor Green
