<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Azure.Core" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
    <PackageReference Include="Azure.ResourceManager.CognitiveServices" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" />
    <PackageReference Include="Imagile.Framework.Configuration" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoundryGate.Data\FoundryGate.Data.csproj" />
    <ProjectReference Include="..\FoundryGate.Domain\FoundryGate.Domain.csproj" />
  </ItemGroup>

</Project>
