using Microsoft.SqlServer.Dac;

namespace FoundryGate.Cli.Commands.Db.Compare;

/// <summary>
/// The <see cref="DacDeployOptions"/> <c>db compare</c> runs the DacFx <c>SchemaComparison</c> with, in
/// one place so the object-type scoping is unit-testable rather than buried in the command action —
/// same pattern as <c>DacpacDeployOptions</c> next to <c>db deploy</c>.
/// </summary>
/// <remarks>
/// CONVENTIONS.md's schema pipeline is table-shape only (columns, primary/foreign keys, indexes — none
/// of which are separate DacFx <see cref="ObjectType"/> values; they live inside the
/// <see cref="ObjectType.Tables"/> object). Everything else DacFx can compare — logins, users,
/// permissions, role memberships, stored procedures, and so on, none of which this repo's
/// <c>dbo/Tables/*.sql</c> files or the checked-in EF model represent — must never show up as a
/// difference or get regenerated by <c>--apply</c>, so every other <see cref="ObjectType"/> is excluded.
/// </remarks>
public static class SchemaCompareOptions
{
    /// <summary>The only DacFx object type this comparison looks at.</summary>
    public static readonly IReadOnlyList<ObjectType> IncludedObjectTypes = [ObjectType.Tables];

    /// <summary>Every <see cref="ObjectType"/> value except <see cref="IncludedObjectTypes"/>.</summary>
    public static readonly IReadOnlyList<ObjectType> ExcludedObjectTypes =
        [.. Enum.GetValues<ObjectType>().Where(type => !IncludedObjectTypes.Contains(type))];

    /// <summary>Builds the options for one comparison.</summary>
    public static DacDeployOptions Create() => new()
    {
        ExcludeObjectTypes = [.. ExcludedObjectTypes],
        // Regenerating a table script always rewrites its full column list in the EF model's
        // declaration order, so plain reordering carries no signal — treat it as no difference at all
        // rather than flagging it and rewriting the file for nothing.
        IgnoreColumnOrder = true,
        IgnoreWhitespace = true,
        IgnoreComments = true
    };
}
